// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plc_memory.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fplc_5fmemory_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fplc_5fmemory_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fplc_5fmemory_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fplc_5fmemory_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fplc_5fmemory_2eproto;
namespace iot {
namespace honeypot {
class PLCMemory;
struct PLCMemoryDefaultTypeInternal;
extern PLCMemoryDefaultTypeInternal _PLCMemory_default_instance_;
class PLCMemory_CountersEntry_DoNotUse;
struct PLCMemory_CountersEntry_DoNotUseDefaultTypeInternal;
extern PLCMemory_CountersEntry_DoNotUseDefaultTypeInternal _PLCMemory_CountersEntry_DoNotUse_default_instance_;
class PLCMemory_DataRegistersEntry_DoNotUse;
struct PLCMemory_DataRegistersEntry_DoNotUseDefaultTypeInternal;
extern PLCMemory_DataRegistersEntry_DoNotUseDefaultTypeInternal _PLCMemory_DataRegistersEntry_DoNotUse_default_instance_;
class PLCMemory_RetentiveMemoryEntry_DoNotUse;
struct PLCMemory_RetentiveMemoryEntry_DoNotUseDefaultTypeInternal;
extern PLCMemory_RetentiveMemoryEntry_DoNotUseDefaultTypeInternal _PLCMemory_RetentiveMemoryEntry_DoNotUse_default_instance_;
class PLCMemory_TimerCounter;
struct PLCMemory_TimerCounterDefaultTypeInternal;
extern PLCMemory_TimerCounterDefaultTypeInternal _PLCMemory_TimerCounter_default_instance_;
class PLCMemory_TimersEntry_DoNotUse;
struct PLCMemory_TimersEntry_DoNotUseDefaultTypeInternal;
extern PLCMemory_TimersEntry_DoNotUseDefaultTypeInternal _PLCMemory_TimersEntry_DoNotUse_default_instance_;
class PLCMemory_WorkMemoryEntry_DoNotUse;
struct PLCMemory_WorkMemoryEntry_DoNotUseDefaultTypeInternal;
extern PLCMemory_WorkMemoryEntry_DoNotUseDefaultTypeInternal _PLCMemory_WorkMemoryEntry_DoNotUse_default_instance_;
}  // namespace honeypot
}  // namespace iot
PROTOBUF_NAMESPACE_OPEN
template<> ::iot::honeypot::PLCMemory* Arena::CreateMaybeMessage<::iot::honeypot::PLCMemory>(Arena*);
template<> ::iot::honeypot::PLCMemory_CountersEntry_DoNotUse* Arena::CreateMaybeMessage<::iot::honeypot::PLCMemory_CountersEntry_DoNotUse>(Arena*);
template<> ::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse* Arena::CreateMaybeMessage<::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse>(Arena*);
template<> ::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse* Arena::CreateMaybeMessage<::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse>(Arena*);
template<> ::iot::honeypot::PLCMemory_TimerCounter* Arena::CreateMaybeMessage<::iot::honeypot::PLCMemory_TimerCounter>(Arena*);
template<> ::iot::honeypot::PLCMemory_TimersEntry_DoNotUse* Arena::CreateMaybeMessage<::iot::honeypot::PLCMemory_TimersEntry_DoNotUse>(Arena*);
template<> ::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse* Arena::CreateMaybeMessage<::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace iot {
namespace honeypot {

// ===================================================================

class PLCMemory_WorkMemoryEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_WorkMemoryEntry_DoNotUse, 
    std::string, uint32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_WorkMemoryEntry_DoNotUse, 
    std::string, uint32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> SuperType;
  PLCMemory_WorkMemoryEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR PLCMemory_WorkMemoryEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit PLCMemory_WorkMemoryEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PLCMemory_WorkMemoryEntry_DoNotUse& other);
  static const PLCMemory_WorkMemoryEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PLCMemory_WorkMemoryEntry_DoNotUse*>(&_PLCMemory_WorkMemoryEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "iot.honeypot.PLCMemory.WorkMemoryEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fplc_5fmemory_2eproto;
};

// -------------------------------------------------------------------

class PLCMemory_RetentiveMemoryEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_RetentiveMemoryEntry_DoNotUse, 
    std::string, uint32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_RetentiveMemoryEntry_DoNotUse, 
    std::string, uint32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> SuperType;
  PLCMemory_RetentiveMemoryEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR PLCMemory_RetentiveMemoryEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit PLCMemory_RetentiveMemoryEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PLCMemory_RetentiveMemoryEntry_DoNotUse& other);
  static const PLCMemory_RetentiveMemoryEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PLCMemory_RetentiveMemoryEntry_DoNotUse*>(&_PLCMemory_RetentiveMemoryEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "iot.honeypot.PLCMemory.RetentiveMemoryEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fplc_5fmemory_2eproto;
};

// -------------------------------------------------------------------

class PLCMemory_DataRegistersEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_DataRegistersEntry_DoNotUse, 
    std::string, uint32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_DataRegistersEntry_DoNotUse, 
    std::string, uint32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> SuperType;
  PLCMemory_DataRegistersEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR PLCMemory_DataRegistersEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit PLCMemory_DataRegistersEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PLCMemory_DataRegistersEntry_DoNotUse& other);
  static const PLCMemory_DataRegistersEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PLCMemory_DataRegistersEntry_DoNotUse*>(&_PLCMemory_DataRegistersEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "iot.honeypot.PLCMemory.DataRegistersEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fplc_5fmemory_2eproto;
};

// -------------------------------------------------------------------

class PLCMemory_TimerCounter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:iot.honeypot.PLCMemory.TimerCounter) */ {
 public:
  inline PLCMemory_TimerCounter() : PLCMemory_TimerCounter(nullptr) {}
  ~PLCMemory_TimerCounter() override;
  explicit PROTOBUF_CONSTEXPR PLCMemory_TimerCounter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PLCMemory_TimerCounter(const PLCMemory_TimerCounter& from);
  PLCMemory_TimerCounter(PLCMemory_TimerCounter&& from) noexcept
    : PLCMemory_TimerCounter() {
    *this = ::std::move(from);
  }

  inline PLCMemory_TimerCounter& operator=(const PLCMemory_TimerCounter& from) {
    CopyFrom(from);
    return *this;
  }
  inline PLCMemory_TimerCounter& operator=(PLCMemory_TimerCounter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PLCMemory_TimerCounter& default_instance() {
    return *internal_default_instance();
  }
  static inline const PLCMemory_TimerCounter* internal_default_instance() {
    return reinterpret_cast<const PLCMemory_TimerCounter*>(
               &_PLCMemory_TimerCounter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PLCMemory_TimerCounter& a, PLCMemory_TimerCounter& b) {
    a.Swap(&b);
  }
  inline void Swap(PLCMemory_TimerCounter* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PLCMemory_TimerCounter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PLCMemory_TimerCounter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PLCMemory_TimerCounter>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PLCMemory_TimerCounter& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PLCMemory_TimerCounter& from) {
    PLCMemory_TimerCounter::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PLCMemory_TimerCounter* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "iot.honeypot.PLCMemory.TimerCounter";
  }
  protected:
  explicit PLCMemory_TimerCounter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPresetValueFieldNumber = 1,
    kCurrentValueFieldNumber = 2,
    kEnabledFieldNumber = 3,
  };
  // uint32 preset_value = 1;
  void clear_preset_value();
  uint32_t preset_value() const;
  void set_preset_value(uint32_t value);
  private:
  uint32_t _internal_preset_value() const;
  void _internal_set_preset_value(uint32_t value);
  public:

  // uint32 current_value = 2;
  void clear_current_value();
  uint32_t current_value() const;
  void set_current_value(uint32_t value);
  private:
  uint32_t _internal_current_value() const;
  void _internal_set_current_value(uint32_t value);
  public:

  // bool enabled = 3;
  void clear_enabled();
  bool enabled() const;
  void set_enabled(bool value);
  private:
  bool _internal_enabled() const;
  void _internal_set_enabled(bool value);
  public:

  // @@protoc_insertion_point(class_scope:iot.honeypot.PLCMemory.TimerCounter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t preset_value_;
    uint32_t current_value_;
    bool enabled_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fplc_5fmemory_2eproto;
};
// -------------------------------------------------------------------

class PLCMemory_TimersEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_TimersEntry_DoNotUse, 
    std::string, ::iot::honeypot::PLCMemory_TimerCounter,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_TimersEntry_DoNotUse, 
    std::string, ::iot::honeypot::PLCMemory_TimerCounter,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  PLCMemory_TimersEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR PLCMemory_TimersEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit PLCMemory_TimersEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PLCMemory_TimersEntry_DoNotUse& other);
  static const PLCMemory_TimersEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PLCMemory_TimersEntry_DoNotUse*>(&_PLCMemory_TimersEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "iot.honeypot.PLCMemory.TimersEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fplc_5fmemory_2eproto;
};

// -------------------------------------------------------------------

class PLCMemory_CountersEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_CountersEntry_DoNotUse, 
    std::string, ::iot::honeypot::PLCMemory_TimerCounter,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PLCMemory_CountersEntry_DoNotUse, 
    std::string, ::iot::honeypot::PLCMemory_TimerCounter,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  PLCMemory_CountersEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR PLCMemory_CountersEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit PLCMemory_CountersEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PLCMemory_CountersEntry_DoNotUse& other);
  static const PLCMemory_CountersEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PLCMemory_CountersEntry_DoNotUse*>(&_PLCMemory_CountersEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "iot.honeypot.PLCMemory.CountersEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fplc_5fmemory_2eproto;
};

// -------------------------------------------------------------------

class PLCMemory final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:iot.honeypot.PLCMemory) */ {
 public:
  inline PLCMemory() : PLCMemory(nullptr) {}
  ~PLCMemory() override;
  explicit PROTOBUF_CONSTEXPR PLCMemory(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PLCMemory(const PLCMemory& from);
  PLCMemory(PLCMemory&& from) noexcept
    : PLCMemory() {
    *this = ::std::move(from);
  }

  inline PLCMemory& operator=(const PLCMemory& from) {
    CopyFrom(from);
    return *this;
  }
  inline PLCMemory& operator=(PLCMemory&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PLCMemory& default_instance() {
    return *internal_default_instance();
  }
  static inline const PLCMemory* internal_default_instance() {
    return reinterpret_cast<const PLCMemory*>(
               &_PLCMemory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(PLCMemory& a, PLCMemory& b) {
    a.Swap(&b);
  }
  inline void Swap(PLCMemory* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PLCMemory* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PLCMemory* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PLCMemory>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PLCMemory& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PLCMemory& from) {
    PLCMemory::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PLCMemory* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "iot.honeypot.PLCMemory";
  }
  protected:
  explicit PLCMemory(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PLCMemory_TimerCounter TimerCounter;

  // accessors -------------------------------------------------------

  enum : int {
    kWorkMemoryFieldNumber = 3,
    kRetentiveMemoryFieldNumber = 4,
    kDataRegistersFieldNumber = 5,
    kTimersFieldNumber = 6,
    kCountersFieldNumber = 7,
    kInputRegionFieldNumber = 1,
    kOutputRegionFieldNumber = 2,
  };
  // map<string, uint32> work_memory = 3;
  int work_memory_size() const;
  private:
  int _internal_work_memory_size() const;
  public:
  void clear_work_memory();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
      _internal_work_memory() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
      _internal_mutable_work_memory();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
      work_memory() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
      mutable_work_memory();

  // map<string, uint32> retentive_memory = 4;
  int retentive_memory_size() const;
  private:
  int _internal_retentive_memory_size() const;
  public:
  void clear_retentive_memory();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
      _internal_retentive_memory() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
      _internal_mutable_retentive_memory();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
      retentive_memory() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
      mutable_retentive_memory();

  // map<string, uint32> data_registers = 5;
  int data_registers_size() const;
  private:
  int _internal_data_registers_size() const;
  public:
  void clear_data_registers();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
      _internal_data_registers() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
      _internal_mutable_data_registers();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
      data_registers() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
      mutable_data_registers();

  // map<string, .iot.honeypot.PLCMemory.TimerCounter> timers = 6;
  int timers_size() const;
  private:
  int _internal_timers_size() const;
  public:
  void clear_timers();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >&
      _internal_timers() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >*
      _internal_mutable_timers();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >&
      timers() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >*
      mutable_timers();

  // map<string, .iot.honeypot.PLCMemory.TimerCounter> counters = 7;
  int counters_size() const;
  private:
  int _internal_counters_size() const;
  public:
  void clear_counters();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >&
      _internal_counters() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >*
      _internal_mutable_counters();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >&
      counters() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >*
      mutable_counters();

  // bytes input_region = 1;
  void clear_input_region();
  const std::string& input_region() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_input_region(ArgT0&& arg0, ArgT... args);
  std::string* mutable_input_region();
  PROTOBUF_NODISCARD std::string* release_input_region();
  void set_allocated_input_region(std::string* input_region);
  private:
  const std::string& _internal_input_region() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_input_region(const std::string& value);
  std::string* _internal_mutable_input_region();
  public:

  // bytes output_region = 2;
  void clear_output_region();
  const std::string& output_region() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_output_region(ArgT0&& arg0, ArgT... args);
  std::string* mutable_output_region();
  PROTOBUF_NODISCARD std::string* release_output_region();
  void set_allocated_output_region(std::string* output_region);
  private:
  const std::string& _internal_output_region() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_output_region(const std::string& value);
  std::string* _internal_mutable_output_region();
  public:

  // @@protoc_insertion_point(class_scope:iot.honeypot.PLCMemory)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        PLCMemory_WorkMemoryEntry_DoNotUse,
        std::string, uint32_t,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> work_memory_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        PLCMemory_RetentiveMemoryEntry_DoNotUse,
        std::string, uint32_t,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> retentive_memory_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        PLCMemory_DataRegistersEntry_DoNotUse,
        std::string, uint32_t,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32> data_registers_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        PLCMemory_TimersEntry_DoNotUse,
        std::string, ::iot::honeypot::PLCMemory_TimerCounter,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> timers_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        PLCMemory_CountersEntry_DoNotUse,
        std::string, ::iot::honeypot::PLCMemory_TimerCounter,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> counters_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr input_region_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_region_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fplc_5fmemory_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PLCMemory_TimerCounter

// uint32 preset_value = 1;
inline void PLCMemory_TimerCounter::clear_preset_value() {
  _impl_.preset_value_ = 0u;
}
inline uint32_t PLCMemory_TimerCounter::_internal_preset_value() const {
  return _impl_.preset_value_;
}
inline uint32_t PLCMemory_TimerCounter::preset_value() const {
  // @@protoc_insertion_point(field_get:iot.honeypot.PLCMemory.TimerCounter.preset_value)
  return _internal_preset_value();
}
inline void PLCMemory_TimerCounter::_internal_set_preset_value(uint32_t value) {
  
  _impl_.preset_value_ = value;
}
inline void PLCMemory_TimerCounter::set_preset_value(uint32_t value) {
  _internal_set_preset_value(value);
  // @@protoc_insertion_point(field_set:iot.honeypot.PLCMemory.TimerCounter.preset_value)
}

// uint32 current_value = 2;
inline void PLCMemory_TimerCounter::clear_current_value() {
  _impl_.current_value_ = 0u;
}
inline uint32_t PLCMemory_TimerCounter::_internal_current_value() const {
  return _impl_.current_value_;
}
inline uint32_t PLCMemory_TimerCounter::current_value() const {
  // @@protoc_insertion_point(field_get:iot.honeypot.PLCMemory.TimerCounter.current_value)
  return _internal_current_value();
}
inline void PLCMemory_TimerCounter::_internal_set_current_value(uint32_t value) {
  
  _impl_.current_value_ = value;
}
inline void PLCMemory_TimerCounter::set_current_value(uint32_t value) {
  _internal_set_current_value(value);
  // @@protoc_insertion_point(field_set:iot.honeypot.PLCMemory.TimerCounter.current_value)
}

// bool enabled = 3;
inline void PLCMemory_TimerCounter::clear_enabled() {
  _impl_.enabled_ = false;
}
inline bool PLCMemory_TimerCounter::_internal_enabled() const {
  return _impl_.enabled_;
}
inline bool PLCMemory_TimerCounter::enabled() const {
  // @@protoc_insertion_point(field_get:iot.honeypot.PLCMemory.TimerCounter.enabled)
  return _internal_enabled();
}
inline void PLCMemory_TimerCounter::_internal_set_enabled(bool value) {
  
  _impl_.enabled_ = value;
}
inline void PLCMemory_TimerCounter::set_enabled(bool value) {
  _internal_set_enabled(value);
  // @@protoc_insertion_point(field_set:iot.honeypot.PLCMemory.TimerCounter.enabled)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PLCMemory

// bytes input_region = 1;
inline void PLCMemory::clear_input_region() {
  _impl_.input_region_.ClearToEmpty();
}
inline const std::string& PLCMemory::input_region() const {
  // @@protoc_insertion_point(field_get:iot.honeypot.PLCMemory.input_region)
  return _internal_input_region();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PLCMemory::set_input_region(ArgT0&& arg0, ArgT... args) {
 
 _impl_.input_region_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:iot.honeypot.PLCMemory.input_region)
}
inline std::string* PLCMemory::mutable_input_region() {
  std::string* _s = _internal_mutable_input_region();
  // @@protoc_insertion_point(field_mutable:iot.honeypot.PLCMemory.input_region)
  return _s;
}
inline const std::string& PLCMemory::_internal_input_region() const {
  return _impl_.input_region_.Get();
}
inline void PLCMemory::_internal_set_input_region(const std::string& value) {
  
  _impl_.input_region_.Set(value, GetArenaForAllocation());
}
inline std::string* PLCMemory::_internal_mutable_input_region() {
  
  return _impl_.input_region_.Mutable(GetArenaForAllocation());
}
inline std::string* PLCMemory::release_input_region() {
  // @@protoc_insertion_point(field_release:iot.honeypot.PLCMemory.input_region)
  return _impl_.input_region_.Release();
}
inline void PLCMemory::set_allocated_input_region(std::string* input_region) {
  if (input_region != nullptr) {
    
  } else {
    
  }
  _impl_.input_region_.SetAllocated(input_region, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.input_region_.IsDefault()) {
    _impl_.input_region_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:iot.honeypot.PLCMemory.input_region)
}

// bytes output_region = 2;
inline void PLCMemory::clear_output_region() {
  _impl_.output_region_.ClearToEmpty();
}
inline const std::string& PLCMemory::output_region() const {
  // @@protoc_insertion_point(field_get:iot.honeypot.PLCMemory.output_region)
  return _internal_output_region();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PLCMemory::set_output_region(ArgT0&& arg0, ArgT... args) {
 
 _impl_.output_region_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:iot.honeypot.PLCMemory.output_region)
}
inline std::string* PLCMemory::mutable_output_region() {
  std::string* _s = _internal_mutable_output_region();
  // @@protoc_insertion_point(field_mutable:iot.honeypot.PLCMemory.output_region)
  return _s;
}
inline const std::string& PLCMemory::_internal_output_region() const {
  return _impl_.output_region_.Get();
}
inline void PLCMemory::_internal_set_output_region(const std::string& value) {
  
  _impl_.output_region_.Set(value, GetArenaForAllocation());
}
inline std::string* PLCMemory::_internal_mutable_output_region() {
  
  return _impl_.output_region_.Mutable(GetArenaForAllocation());
}
inline std::string* PLCMemory::release_output_region() {
  // @@protoc_insertion_point(field_release:iot.honeypot.PLCMemory.output_region)
  return _impl_.output_region_.Release();
}
inline void PLCMemory::set_allocated_output_region(std::string* output_region) {
  if (output_region != nullptr) {
    
  } else {
    
  }
  _impl_.output_region_.SetAllocated(output_region, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.output_region_.IsDefault()) {
    _impl_.output_region_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:iot.honeypot.PLCMemory.output_region)
}

// map<string, uint32> work_memory = 3;
inline int PLCMemory::_internal_work_memory_size() const {
  return _impl_.work_memory_.size();
}
inline int PLCMemory::work_memory_size() const {
  return _internal_work_memory_size();
}
inline void PLCMemory::clear_work_memory() {
  _impl_.work_memory_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
PLCMemory::_internal_work_memory() const {
  return _impl_.work_memory_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
PLCMemory::work_memory() const {
  // @@protoc_insertion_point(field_map:iot.honeypot.PLCMemory.work_memory)
  return _internal_work_memory();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
PLCMemory::_internal_mutable_work_memory() {
  return _impl_.work_memory_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
PLCMemory::mutable_work_memory() {
  // @@protoc_insertion_point(field_mutable_map:iot.honeypot.PLCMemory.work_memory)
  return _internal_mutable_work_memory();
}

// map<string, uint32> retentive_memory = 4;
inline int PLCMemory::_internal_retentive_memory_size() const {
  return _impl_.retentive_memory_.size();
}
inline int PLCMemory::retentive_memory_size() const {
  return _internal_retentive_memory_size();
}
inline void PLCMemory::clear_retentive_memory() {
  _impl_.retentive_memory_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
PLCMemory::_internal_retentive_memory() const {
  return _impl_.retentive_memory_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
PLCMemory::retentive_memory() const {
  // @@protoc_insertion_point(field_map:iot.honeypot.PLCMemory.retentive_memory)
  return _internal_retentive_memory();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
PLCMemory::_internal_mutable_retentive_memory() {
  return _impl_.retentive_memory_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
PLCMemory::mutable_retentive_memory() {
  // @@protoc_insertion_point(field_mutable_map:iot.honeypot.PLCMemory.retentive_memory)
  return _internal_mutable_retentive_memory();
}

// map<string, uint32> data_registers = 5;
inline int PLCMemory::_internal_data_registers_size() const {
  return _impl_.data_registers_.size();
}
inline int PLCMemory::data_registers_size() const {
  return _internal_data_registers_size();
}
inline void PLCMemory::clear_data_registers() {
  _impl_.data_registers_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
PLCMemory::_internal_data_registers() const {
  return _impl_.data_registers_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >&
PLCMemory::data_registers() const {
  // @@protoc_insertion_point(field_map:iot.honeypot.PLCMemory.data_registers)
  return _internal_data_registers();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
PLCMemory::_internal_mutable_data_registers() {
  return _impl_.data_registers_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >*
PLCMemory::mutable_data_registers() {
  // @@protoc_insertion_point(field_mutable_map:iot.honeypot.PLCMemory.data_registers)
  return _internal_mutable_data_registers();
}

// map<string, .iot.honeypot.PLCMemory.TimerCounter> timers = 6;
inline int PLCMemory::_internal_timers_size() const {
  return _impl_.timers_.size();
}
inline int PLCMemory::timers_size() const {
  return _internal_timers_size();
}
inline void PLCMemory::clear_timers() {
  _impl_.timers_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >&
PLCMemory::_internal_timers() const {
  return _impl_.timers_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >&
PLCMemory::timers() const {
  // @@protoc_insertion_point(field_map:iot.honeypot.PLCMemory.timers)
  return _internal_timers();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >*
PLCMemory::_internal_mutable_timers() {
  return _impl_.timers_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >*
PLCMemory::mutable_timers() {
  // @@protoc_insertion_point(field_mutable_map:iot.honeypot.PLCMemory.timers)
  return _internal_mutable_timers();
}

// map<string, .iot.honeypot.PLCMemory.TimerCounter> counters = 7;
inline int PLCMemory::_internal_counters_size() const {
  return _impl_.counters_.size();
}
inline int PLCMemory::counters_size() const {
  return _internal_counters_size();
}
inline void PLCMemory::clear_counters() {
  _impl_.counters_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >&
PLCMemory::_internal_counters() const {
  return _impl_.counters_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >&
PLCMemory::counters() const {
  // @@protoc_insertion_point(field_map:iot.honeypot.PLCMemory.counters)
  return _internal_counters();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >*
PLCMemory::_internal_mutable_counters() {
  return _impl_.counters_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >*
PLCMemory::mutable_counters() {
  // @@protoc_insertion_point(field_mutable_map:iot.honeypot.PLCMemory.counters)
  return _internal_mutable_counters();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace honeypot
}  // namespace iot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fplc_5fmemory_2eproto
