// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plc_memory.proto

#include "proto/plc_memory.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace iot {
namespace honeypot {
PROTOBUF_CONSTEXPR PLCMemory_WorkMemoryEntry_DoNotUse::PLCMemory_WorkMemoryEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct PLCMemory_WorkMemoryEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PLCMemory_WorkMemoryEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PLCMemory_WorkMemoryEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PLCMemory_WorkMemoryEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PLCMemory_WorkMemoryEntry_DoNotUseDefaultTypeInternal _PLCMemory_WorkMemoryEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR PLCMemory_RetentiveMemoryEntry_DoNotUse::PLCMemory_RetentiveMemoryEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct PLCMemory_RetentiveMemoryEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PLCMemory_RetentiveMemoryEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PLCMemory_RetentiveMemoryEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PLCMemory_RetentiveMemoryEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PLCMemory_RetentiveMemoryEntry_DoNotUseDefaultTypeInternal _PLCMemory_RetentiveMemoryEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR PLCMemory_DataRegistersEntry_DoNotUse::PLCMemory_DataRegistersEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct PLCMemory_DataRegistersEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PLCMemory_DataRegistersEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PLCMemory_DataRegistersEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PLCMemory_DataRegistersEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PLCMemory_DataRegistersEntry_DoNotUseDefaultTypeInternal _PLCMemory_DataRegistersEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR PLCMemory_TimerCounter::PLCMemory_TimerCounter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.preset_value_)*/0u
  , /*decltype(_impl_.current_value_)*/0u
  , /*decltype(_impl_.enabled_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PLCMemory_TimerCounterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PLCMemory_TimerCounterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PLCMemory_TimerCounterDefaultTypeInternal() {}
  union {
    PLCMemory_TimerCounter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PLCMemory_TimerCounterDefaultTypeInternal _PLCMemory_TimerCounter_default_instance_;
PROTOBUF_CONSTEXPR PLCMemory_TimersEntry_DoNotUse::PLCMemory_TimersEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct PLCMemory_TimersEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PLCMemory_TimersEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PLCMemory_TimersEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PLCMemory_TimersEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PLCMemory_TimersEntry_DoNotUseDefaultTypeInternal _PLCMemory_TimersEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR PLCMemory_CountersEntry_DoNotUse::PLCMemory_CountersEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct PLCMemory_CountersEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PLCMemory_CountersEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PLCMemory_CountersEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PLCMemory_CountersEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PLCMemory_CountersEntry_DoNotUseDefaultTypeInternal _PLCMemory_CountersEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR PLCMemory::PLCMemory(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.work_memory_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.retentive_memory_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.data_registers_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.timers_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.counters_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.input_region_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.output_region_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PLCMemoryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PLCMemoryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PLCMemoryDefaultTypeInternal() {}
  union {
    PLCMemory _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PLCMemoryDefaultTypeInternal _PLCMemory_default_instance_;
}  // namespace honeypot
}  // namespace iot
static ::_pb::Metadata file_level_metadata_proto_2fplc_5fmemory_2eproto[7];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fplc_5fmemory_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fplc_5fmemory_2eproto = nullptr;

const uint32_t TableStruct_proto_2fplc_5fmemory_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_TimerCounter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_TimerCounter, _impl_.preset_value_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_TimerCounter, _impl_.current_value_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_TimerCounter, _impl_.enabled_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_TimersEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_TimersEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_TimersEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_TimersEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_CountersEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_CountersEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_CountersEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory_CountersEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory, _impl_.input_region_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory, _impl_.output_region_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory, _impl_.work_memory_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory, _impl_.retentive_memory_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory, _impl_.data_registers_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory, _impl_.timers_),
  PROTOBUF_FIELD_OFFSET(::iot::honeypot::PLCMemory, _impl_.counters_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse)},
  { 10, 18, -1, sizeof(::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse)},
  { 20, 28, -1, sizeof(::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse)},
  { 30, -1, -1, sizeof(::iot::honeypot::PLCMemory_TimerCounter)},
  { 39, 47, -1, sizeof(::iot::honeypot::PLCMemory_TimersEntry_DoNotUse)},
  { 49, 57, -1, sizeof(::iot::honeypot::PLCMemory_CountersEntry_DoNotUse)},
  { 59, -1, -1, sizeof(::iot::honeypot::PLCMemory)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::iot::honeypot::_PLCMemory_WorkMemoryEntry_DoNotUse_default_instance_._instance,
  &::iot::honeypot::_PLCMemory_RetentiveMemoryEntry_DoNotUse_default_instance_._instance,
  &::iot::honeypot::_PLCMemory_DataRegistersEntry_DoNotUse_default_instance_._instance,
  &::iot::honeypot::_PLCMemory_TimerCounter_default_instance_._instance,
  &::iot::honeypot::_PLCMemory_TimersEntry_DoNotUse_default_instance_._instance,
  &::iot::honeypot::_PLCMemory_CountersEntry_DoNotUse_default_instance_._instance,
  &::iot::honeypot::_PLCMemory_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fplc_5fmemory_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026proto/plc_memory.proto\022\014iot.honeypot\"\213"
  "\006\n\tPLCMemory\022\024\n\014input_region\030\001 \001(\014\022\025\n\rou"
  "tput_region\030\002 \001(\014\022<\n\013work_memory\030\003 \003(\0132\'"
  ".iot.honeypot.PLCMemory.WorkMemoryEntry\022"
  "F\n\020retentive_memory\030\004 \003(\0132,.iot.honeypot"
  ".PLCMemory.RetentiveMemoryEntry\022B\n\016data_"
  "registers\030\005 \003(\0132*.iot.honeypot.PLCMemory"
  ".DataRegistersEntry\0223\n\006timers\030\006 \003(\0132#.io"
  "t.honeypot.PLCMemory.TimersEntry\0227\n\010coun"
  "ters\030\007 \003(\0132%.iot.honeypot.PLCMemory.Coun"
  "tersEntry\0321\n\017WorkMemoryEntry\022\013\n\003key\030\001 \001("
  "\t\022\r\n\005value\030\002 \001(\r:\0028\001\0326\n\024RetentiveMemoryE"
  "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\r:\0028\001\0324\n\022"
  "DataRegistersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value"
  "\030\002 \001(\r:\0028\001\032L\n\014TimerCounter\022\024\n\014preset_val"
  "ue\030\001 \001(\r\022\025\n\rcurrent_value\030\002 \001(\r\022\017\n\007enabl"
  "ed\030\003 \001(\010\032S\n\013TimersEntry\022\013\n\003key\030\001 \001(\t\0223\n\005"
  "value\030\002 \001(\0132$.iot.honeypot.PLCMemory.Tim"
  "erCounter:\0028\001\032U\n\rCountersEntry\022\013\n\003key\030\001 "
  "\001(\t\0223\n\005value\030\002 \001(\0132$.iot.honeypot.PLCMem"
  "ory.TimerCounter:\0028\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2fplc_5fmemory_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fplc_5fmemory_2eproto = {
    false, false, 828, descriptor_table_protodef_proto_2fplc_5fmemory_2eproto,
    "proto/plc_memory.proto",
    &descriptor_table_proto_2fplc_5fmemory_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_proto_2fplc_5fmemory_2eproto::offsets,
    file_level_metadata_proto_2fplc_5fmemory_2eproto, file_level_enum_descriptors_proto_2fplc_5fmemory_2eproto,
    file_level_service_descriptors_proto_2fplc_5fmemory_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fplc_5fmemory_2eproto_getter() {
  return &descriptor_table_proto_2fplc_5fmemory_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fplc_5fmemory_2eproto(&descriptor_table_proto_2fplc_5fmemory_2eproto);
namespace iot {
namespace honeypot {

// ===================================================================

PLCMemory_WorkMemoryEntry_DoNotUse::PLCMemory_WorkMemoryEntry_DoNotUse() {}
PLCMemory_WorkMemoryEntry_DoNotUse::PLCMemory_WorkMemoryEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void PLCMemory_WorkMemoryEntry_DoNotUse::MergeFrom(const PLCMemory_WorkMemoryEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata PLCMemory_WorkMemoryEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fplc_5fmemory_2eproto_getter, &descriptor_table_proto_2fplc_5fmemory_2eproto_once,
      file_level_metadata_proto_2fplc_5fmemory_2eproto[0]);
}

// ===================================================================

PLCMemory_RetentiveMemoryEntry_DoNotUse::PLCMemory_RetentiveMemoryEntry_DoNotUse() {}
PLCMemory_RetentiveMemoryEntry_DoNotUse::PLCMemory_RetentiveMemoryEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void PLCMemory_RetentiveMemoryEntry_DoNotUse::MergeFrom(const PLCMemory_RetentiveMemoryEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata PLCMemory_RetentiveMemoryEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fplc_5fmemory_2eproto_getter, &descriptor_table_proto_2fplc_5fmemory_2eproto_once,
      file_level_metadata_proto_2fplc_5fmemory_2eproto[1]);
}

// ===================================================================

PLCMemory_DataRegistersEntry_DoNotUse::PLCMemory_DataRegistersEntry_DoNotUse() {}
PLCMemory_DataRegistersEntry_DoNotUse::PLCMemory_DataRegistersEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void PLCMemory_DataRegistersEntry_DoNotUse::MergeFrom(const PLCMemory_DataRegistersEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata PLCMemory_DataRegistersEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fplc_5fmemory_2eproto_getter, &descriptor_table_proto_2fplc_5fmemory_2eproto_once,
      file_level_metadata_proto_2fplc_5fmemory_2eproto[2]);
}

// ===================================================================

class PLCMemory_TimerCounter::_Internal {
 public:
};

PLCMemory_TimerCounter::PLCMemory_TimerCounter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:iot.honeypot.PLCMemory.TimerCounter)
}
PLCMemory_TimerCounter::PLCMemory_TimerCounter(const PLCMemory_TimerCounter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PLCMemory_TimerCounter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.preset_value_){}
    , decltype(_impl_.current_value_){}
    , decltype(_impl_.enabled_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.preset_value_, &from._impl_.preset_value_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.enabled_) -
    reinterpret_cast<char*>(&_impl_.preset_value_)) + sizeof(_impl_.enabled_));
  // @@protoc_insertion_point(copy_constructor:iot.honeypot.PLCMemory.TimerCounter)
}

inline void PLCMemory_TimerCounter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.preset_value_){0u}
    , decltype(_impl_.current_value_){0u}
    , decltype(_impl_.enabled_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PLCMemory_TimerCounter::~PLCMemory_TimerCounter() {
  // @@protoc_insertion_point(destructor:iot.honeypot.PLCMemory.TimerCounter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PLCMemory_TimerCounter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PLCMemory_TimerCounter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PLCMemory_TimerCounter::Clear() {
// @@protoc_insertion_point(message_clear_start:iot.honeypot.PLCMemory.TimerCounter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.preset_value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.enabled_) -
      reinterpret_cast<char*>(&_impl_.preset_value_)) + sizeof(_impl_.enabled_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PLCMemory_TimerCounter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 preset_value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.preset_value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 current_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.current_value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool enabled = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.enabled_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PLCMemory_TimerCounter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:iot.honeypot.PLCMemory.TimerCounter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 preset_value = 1;
  if (this->_internal_preset_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_preset_value(), target);
  }

  // uint32 current_value = 2;
  if (this->_internal_current_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_current_value(), target);
  }

  // bool enabled = 3;
  if (this->_internal_enabled() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_enabled(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:iot.honeypot.PLCMemory.TimerCounter)
  return target;
}

size_t PLCMemory_TimerCounter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:iot.honeypot.PLCMemory.TimerCounter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 preset_value = 1;
  if (this->_internal_preset_value() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_preset_value());
  }

  // uint32 current_value = 2;
  if (this->_internal_current_value() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_current_value());
  }

  // bool enabled = 3;
  if (this->_internal_enabled() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PLCMemory_TimerCounter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PLCMemory_TimerCounter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PLCMemory_TimerCounter::GetClassData() const { return &_class_data_; }


void PLCMemory_TimerCounter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PLCMemory_TimerCounter*>(&to_msg);
  auto& from = static_cast<const PLCMemory_TimerCounter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:iot.honeypot.PLCMemory.TimerCounter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_preset_value() != 0) {
    _this->_internal_set_preset_value(from._internal_preset_value());
  }
  if (from._internal_current_value() != 0) {
    _this->_internal_set_current_value(from._internal_current_value());
  }
  if (from._internal_enabled() != 0) {
    _this->_internal_set_enabled(from._internal_enabled());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PLCMemory_TimerCounter::CopyFrom(const PLCMemory_TimerCounter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:iot.honeypot.PLCMemory.TimerCounter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PLCMemory_TimerCounter::IsInitialized() const {
  return true;
}

void PLCMemory_TimerCounter::InternalSwap(PLCMemory_TimerCounter* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PLCMemory_TimerCounter, _impl_.enabled_)
      + sizeof(PLCMemory_TimerCounter::_impl_.enabled_)
      - PROTOBUF_FIELD_OFFSET(PLCMemory_TimerCounter, _impl_.preset_value_)>(
          reinterpret_cast<char*>(&_impl_.preset_value_),
          reinterpret_cast<char*>(&other->_impl_.preset_value_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PLCMemory_TimerCounter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fplc_5fmemory_2eproto_getter, &descriptor_table_proto_2fplc_5fmemory_2eproto_once,
      file_level_metadata_proto_2fplc_5fmemory_2eproto[3]);
}

// ===================================================================

PLCMemory_TimersEntry_DoNotUse::PLCMemory_TimersEntry_DoNotUse() {}
PLCMemory_TimersEntry_DoNotUse::PLCMemory_TimersEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void PLCMemory_TimersEntry_DoNotUse::MergeFrom(const PLCMemory_TimersEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata PLCMemory_TimersEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fplc_5fmemory_2eproto_getter, &descriptor_table_proto_2fplc_5fmemory_2eproto_once,
      file_level_metadata_proto_2fplc_5fmemory_2eproto[4]);
}

// ===================================================================

PLCMemory_CountersEntry_DoNotUse::PLCMemory_CountersEntry_DoNotUse() {}
PLCMemory_CountersEntry_DoNotUse::PLCMemory_CountersEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void PLCMemory_CountersEntry_DoNotUse::MergeFrom(const PLCMemory_CountersEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata PLCMemory_CountersEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fplc_5fmemory_2eproto_getter, &descriptor_table_proto_2fplc_5fmemory_2eproto_once,
      file_level_metadata_proto_2fplc_5fmemory_2eproto[5]);
}

// ===================================================================

class PLCMemory::_Internal {
 public:
};

PLCMemory::PLCMemory(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &PLCMemory::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:iot.honeypot.PLCMemory)
}
PLCMemory::PLCMemory(const PLCMemory& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PLCMemory* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.work_memory_)*/{}
    , /*decltype(_impl_.retentive_memory_)*/{}
    , /*decltype(_impl_.data_registers_)*/{}
    , /*decltype(_impl_.timers_)*/{}
    , /*decltype(_impl_.counters_)*/{}
    , decltype(_impl_.input_region_){}
    , decltype(_impl_.output_region_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.work_memory_.MergeFrom(from._impl_.work_memory_);
  _this->_impl_.retentive_memory_.MergeFrom(from._impl_.retentive_memory_);
  _this->_impl_.data_registers_.MergeFrom(from._impl_.data_registers_);
  _this->_impl_.timers_.MergeFrom(from._impl_.timers_);
  _this->_impl_.counters_.MergeFrom(from._impl_.counters_);
  _impl_.input_region_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.input_region_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_input_region().empty()) {
    _this->_impl_.input_region_.Set(from._internal_input_region(), 
      _this->GetArenaForAllocation());
  }
  _impl_.output_region_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_region_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_output_region().empty()) {
    _this->_impl_.output_region_.Set(from._internal_output_region(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:iot.honeypot.PLCMemory)
}

inline void PLCMemory::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.work_memory_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_.retentive_memory_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_.data_registers_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_.timers_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_.counters_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.input_region_){}
    , decltype(_impl_.output_region_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.input_region_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.input_region_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.output_region_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_region_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PLCMemory::~PLCMemory() {
  // @@protoc_insertion_point(destructor:iot.honeypot.PLCMemory)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void PLCMemory::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.work_memory_.Destruct();
  _impl_.work_memory_.~MapField();
  _impl_.retentive_memory_.Destruct();
  _impl_.retentive_memory_.~MapField();
  _impl_.data_registers_.Destruct();
  _impl_.data_registers_.~MapField();
  _impl_.timers_.Destruct();
  _impl_.timers_.~MapField();
  _impl_.counters_.Destruct();
  _impl_.counters_.~MapField();
  _impl_.input_region_.Destroy();
  _impl_.output_region_.Destroy();
}

void PLCMemory::ArenaDtor(void* object) {
  PLCMemory* _this = reinterpret_cast< PLCMemory* >(object);
  _this->_impl_.work_memory_.Destruct();
  _this->_impl_.retentive_memory_.Destruct();
  _this->_impl_.data_registers_.Destruct();
  _this->_impl_.timers_.Destruct();
  _this->_impl_.counters_.Destruct();
}
void PLCMemory::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PLCMemory::Clear() {
// @@protoc_insertion_point(message_clear_start:iot.honeypot.PLCMemory)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.work_memory_.Clear();
  _impl_.retentive_memory_.Clear();
  _impl_.data_registers_.Clear();
  _impl_.timers_.Clear();
  _impl_.counters_.Clear();
  _impl_.input_region_.ClearToEmpty();
  _impl_.output_region_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PLCMemory::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes input_region = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_input_region();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes output_region = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_output_region();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, uint32> work_memory = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.work_memory_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // map<string, uint32> retentive_memory = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.retentive_memory_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // map<string, uint32> data_registers = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.data_registers_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      // map<string, .iot.honeypot.PLCMemory.TimerCounter> timers = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.timers_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      // map<string, .iot.honeypot.PLCMemory.TimerCounter> counters = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.counters_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PLCMemory::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:iot.honeypot.PLCMemory)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes input_region = 1;
  if (!this->_internal_input_region().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_input_region(), target);
  }

  // bytes output_region = 2;
  if (!this->_internal_output_region().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_output_region(), target);
  }

  // map<string, uint32> work_memory = 3;
  if (!this->_internal_work_memory().empty()) {
    using MapType = ::_pb::Map<std::string, uint32_t>;
    using WireHelper = PLCMemory_WorkMemoryEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_work_memory();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "iot.honeypot.PLCMemory.WorkMemoryEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // map<string, uint32> retentive_memory = 4;
  if (!this->_internal_retentive_memory().empty()) {
    using MapType = ::_pb::Map<std::string, uint32_t>;
    using WireHelper = PLCMemory_RetentiveMemoryEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_retentive_memory();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "iot.honeypot.PLCMemory.RetentiveMemoryEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(4, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(4, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // map<string, uint32> data_registers = 5;
  if (!this->_internal_data_registers().empty()) {
    using MapType = ::_pb::Map<std::string, uint32_t>;
    using WireHelper = PLCMemory_DataRegistersEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_data_registers();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "iot.honeypot.PLCMemory.DataRegistersEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // map<string, .iot.honeypot.PLCMemory.TimerCounter> timers = 6;
  if (!this->_internal_timers().empty()) {
    using MapType = ::_pb::Map<std::string, ::iot::honeypot::PLCMemory_TimerCounter>;
    using WireHelper = PLCMemory_TimersEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_timers();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "iot.honeypot.PLCMemory.TimersEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(6, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(6, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // map<string, .iot.honeypot.PLCMemory.TimerCounter> counters = 7;
  if (!this->_internal_counters().empty()) {
    using MapType = ::_pb::Map<std::string, ::iot::honeypot::PLCMemory_TimerCounter>;
    using WireHelper = PLCMemory_CountersEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_counters();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "iot.honeypot.PLCMemory.CountersEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(7, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(7, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:iot.honeypot.PLCMemory)
  return target;
}

size_t PLCMemory::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:iot.honeypot.PLCMemory)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, uint32> work_memory = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_work_memory_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >::const_iterator
      it = this->_internal_work_memory().begin();
      it != this->_internal_work_memory().end(); ++it) {
    total_size += PLCMemory_WorkMemoryEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<string, uint32> retentive_memory = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_retentive_memory_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >::const_iterator
      it = this->_internal_retentive_memory().begin();
      it != this->_internal_retentive_memory().end(); ++it) {
    total_size += PLCMemory_RetentiveMemoryEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<string, uint32> data_registers = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_data_registers_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, uint32_t >::const_iterator
      it = this->_internal_data_registers().begin();
      it != this->_internal_data_registers().end(); ++it) {
    total_size += PLCMemory_DataRegistersEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<string, .iot.honeypot.PLCMemory.TimerCounter> timers = 6;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_timers_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >::const_iterator
      it = this->_internal_timers().begin();
      it != this->_internal_timers().end(); ++it) {
    total_size += PLCMemory_TimersEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<string, .iot.honeypot.PLCMemory.TimerCounter> counters = 7;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_counters_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::iot::honeypot::PLCMemory_TimerCounter >::const_iterator
      it = this->_internal_counters().begin();
      it != this->_internal_counters().end(); ++it) {
    total_size += PLCMemory_CountersEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // bytes input_region = 1;
  if (!this->_internal_input_region().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_input_region());
  }

  // bytes output_region = 2;
  if (!this->_internal_output_region().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_output_region());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PLCMemory::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PLCMemory::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PLCMemory::GetClassData() const { return &_class_data_; }


void PLCMemory::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PLCMemory*>(&to_msg);
  auto& from = static_cast<const PLCMemory&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:iot.honeypot.PLCMemory)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.work_memory_.MergeFrom(from._impl_.work_memory_);
  _this->_impl_.retentive_memory_.MergeFrom(from._impl_.retentive_memory_);
  _this->_impl_.data_registers_.MergeFrom(from._impl_.data_registers_);
  _this->_impl_.timers_.MergeFrom(from._impl_.timers_);
  _this->_impl_.counters_.MergeFrom(from._impl_.counters_);
  if (!from._internal_input_region().empty()) {
    _this->_internal_set_input_region(from._internal_input_region());
  }
  if (!from._internal_output_region().empty()) {
    _this->_internal_set_output_region(from._internal_output_region());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PLCMemory::CopyFrom(const PLCMemory& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:iot.honeypot.PLCMemory)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PLCMemory::IsInitialized() const {
  return true;
}

void PLCMemory::InternalSwap(PLCMemory* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.work_memory_.InternalSwap(&other->_impl_.work_memory_);
  _impl_.retentive_memory_.InternalSwap(&other->_impl_.retentive_memory_);
  _impl_.data_registers_.InternalSwap(&other->_impl_.data_registers_);
  _impl_.timers_.InternalSwap(&other->_impl_.timers_);
  _impl_.counters_.InternalSwap(&other->_impl_.counters_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.input_region_, lhs_arena,
      &other->_impl_.input_region_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.output_region_, lhs_arena,
      &other->_impl_.output_region_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PLCMemory::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fplc_5fmemory_2eproto_getter, &descriptor_table_proto_2fplc_5fmemory_2eproto_once,
      file_level_metadata_proto_2fplc_5fmemory_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace honeypot
}  // namespace iot
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse*
Arena::CreateMaybeMessage< ::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::iot::honeypot::PLCMemory_WorkMemoryEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse*
Arena::CreateMaybeMessage< ::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::iot::honeypot::PLCMemory_RetentiveMemoryEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse*
Arena::CreateMaybeMessage< ::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::iot::honeypot::PLCMemory_DataRegistersEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::iot::honeypot::PLCMemory_TimerCounter*
Arena::CreateMaybeMessage< ::iot::honeypot::PLCMemory_TimerCounter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::iot::honeypot::PLCMemory_TimerCounter >(arena);
}
template<> PROTOBUF_NOINLINE ::iot::honeypot::PLCMemory_TimersEntry_DoNotUse*
Arena::CreateMaybeMessage< ::iot::honeypot::PLCMemory_TimersEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::iot::honeypot::PLCMemory_TimersEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::iot::honeypot::PLCMemory_CountersEntry_DoNotUse*
Arena::CreateMaybeMessage< ::iot::honeypot::PLCMemory_CountersEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::iot::honeypot::PLCMemory_CountersEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::iot::honeypot::PLCMemory*
Arena::CreateMaybeMessage< ::iot::honeypot::PLCMemory >(Arena* arena) {
  return Arena::CreateMessageInternal< ::iot::honeypot::PLCMemory >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
